// THIS IS A TEMP FILE GENERATED BY StarFruit2.Tests/DummyTest.cs
using StarFruit2;
using StarFruit2.Common;
using System;
using System.CommandLine;
using System.CommandLine.Invocation;
using System.CommandLine.Parsing;
namespace StarFruit2.Tests.TestSampleDatatestName
{
public partial class MyClassCommandSource
: RootCommandSource<MyClass>
{
public MyClassCommandSource()
: base(new Command("", ""))
{
SomeOption = GetSomeOption();
Command.Add(SomeOption);
Command.Handler = CommandHandler.Create(() => { CurrentCommandSource = this; return 0; });
}
protected override  CommandSourceResult GetCommandSourceResult(ParseResult parseResult)
{
return new MyClassCommandSourceResult(parseResult, this);
}
public Option<String> SomeOption { get; set; }
private   Option<String> GetSomeOption()
{
var option = new Option<String>("some-option")
{
Description = "desc",
IsRequired = false,
IsHidden = false,
};
var MyClass_SomeOption_arg = new Argument<String>("some-option");
MyClass_SomeOption_arg.SetDefaultValue("abc");
option.Argument = MyClass_SomeOption_arg;
return option;
}
}
}
